controllers/album.py
from flask import *
from extensions import *
from config import *
import os
import hashlib
import time

album = Blueprint('album', __name__, template_folder='templates')

IMAGE_FOLDER_PREFIX = 'static/images'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'bmp', 'gif'])

def generate_picid(filename, albumid):
	picid = hashlib.md5()
	picid.update(str(albumid).encode('utf-8'))
	picid.update(filename.encode('utf-8'))
	return picid.hexdigest()

def display_photos(cur, albumid):
	db = connect_to_database()
	cur = db.cursor()
	cur.execute('SELECT sequencenum, picid FROM Contain WHERE albumid=%s;', [albumid])
	photos = cur.fetchall()
	picid_format_sequencenum_tuples = []
	for photo in photos:
		picid = photo['picid']
		cur.execute('SELECT format FROM Photo WHERE picid=%s;', [picid])
		pformat = cur.fetchone()['format']
		sequencenum = photo['sequencenum']
		picid_format_sequencenum_tuple = (picid, pformat, sequencenum)
		picid_format_sequencenum_tuples.append(picid_format_sequencenum_tuple)

	sorted(picid_format_sequencenum_tuples, key=lambda instance: instance[2])
	return picid_format_sequencenum_tuples


@album.route('/album/edit', methods=['GET', 'POST'])
def album_edit_route():
	albumid = request.args.get('albumid')
	if albumid is None: 
		abort(404)
	db = connect_to_database()
	cur = db.cursor()
	cur.execute('SELECT albumid FROM Album WHERE albumid=%s;', [albumid])
	number_of_records = cur.rowcount
	if number_of_records != 1:
		abort(404)

	now = time.strftime('%Y-%m-%d', time.localtime(time.time()))

	op = request.form.get('op')
	if op == "add":
		f = request.file['file']
		if f.filename != '':
			filename_extension = f.filename[-3:].lower()
			if filename_extension in ALLOWED_EXTENSIONS:
				picid = generate_picid(f.filename, albumid)

				f.save(os.path.join(IMAGE_FOLDER_PREFIX, picid + '.' + filename_extension))

				try:
					cur.execute('INSERT INTO Photo (picid, format, date) VALUES (%s, %s, %s);', (picid, filename_extension, now))

				except:
					print(cur._last_executed)
					abort(404)

				cur.execute('SELECT sequencenum FROM Contain;')	

				existing_sequencenums = cur.fetchall()
				new_sequencenum = -1
				for existing_sequencenum in existing_sequencenums:
					if new_sequencenum < existing_sequencenum['sequencenum']:
						new_sequencenum = existing_sequencenum['sequencenum']
				new_sequencenum += 1		

				try: 
					cur.execute('INSERT INTO Contain (sequencenum, albumid, picid, caption) VALUES (%s, %s, %s, '');', (new_sequencenum, albumid, picid))
				except:
					print(cur._last_executed)
					abort(404)

				cur.execute('UPDATE Album SET lastupdated=%s WHERE albumid=%s;', (now, albumid))

	elif op = "delete":
		picid = request.form.get('picid')

		cur.execute('SELECT COUNT(sequencenum) FROM Contain WHERE albumid=%s AND picid=%s;', (albumid, picid))
		number_of_records = cur.rowcount
		if number_of_records != 1:
			abort(404)

		#1. delete from Photo
		cur.execute('SELECT format FROM Photo WHERE picid=%s;', [picid])
		pformat = cur.fetchone()['format']
		cur.execute('DELETE FROM Photo WHERE picid=%s;', [picid])

		#2. delete from Contain
		cur.execute('DELETE FROM Contain WHERE albumid=%s AND picid=%s;', (albumid, picid))

		#3. delete from desk
		os.remove(os.path.join(IMAGE_FOLDER_PREFIX, picid + '.' + pformat))

		#4. update Album lastupdated
		cur.execute('UPDATE Album SET lastupdated=%s WHERE albumid=%s;', (now, albumid))

	picid_format_sequencenum_tuples = display_photos(cur, albumid)

	cur.execute('SELECT title FROM Album WHERE albumid=%s;', [albumid])
	title = cur.fetchone()

	options = {
		"edit": True
	}
	return render_template("album.html", picid_format_sequencenum_tuples=picid_format_sequencenum_tuples, title=title, albumid=albumid, **options)

@album.route('/album', methods=['POST', 'GET'])
def album_route():
	albumid = request.args.get('albumid')
	if albumid is None:
		abort(404)

	db = connect_to_database()
	cur = db.cursor()

	cur.execute('SELECT albumid FROM Album WHERE albumid=%s;', [albumid])
	number_of_records = cur.rowcount
	if number_of_records != 1:
		abort(404)

	picid_format_sequencenum_tuples = display_photos(cur, albumid)

	cur.execute('SELECT title FROM Album WHERE albumid=%s;', [albumid])
	title=cur.fetchone()

	options = {
		"edit": False
	}
	return render_template("album.html", picid_format_sequencenum_tuples=picid_format_sequencenum_tuples, title=title, albumid=albumid, **options)

controllers/albums.py
from flask import *
import os
import time
from extensions import connect_to_database

albums = Blueprint('albums', __name__, template_folder='templates')

IMAGE_FOLDER_PREFIX = '/static/images'

@albums.route('/albums/edit', methods = ['GET','POST'])
def albums_edit_route():
	username = request.args.get('username')
	db = connect_to_database()
	cur = db.cursor()
	row_count = cur.execute("SELECT * FROM User WHERE username = %s;", [username])
	if row_count == 0:
		abort(404)

	op=request.form.get('op')

	if op == "delete":
		albumid = request.form.get('albumid')

		#1. delete in Contain
		cur.execute('SELECT picid FROM Contain WHERE albumid=%s;', [albumid])
		picid_to_remove = cur.fetchall()
		cur.execute('DELETE FROM Contain WHERE albumid=%s;', [albumid])

		for picid in picid_to_remove:
			#2. delete in Photo
			pformat = cur.execute('SELECT format FROM Photo WHERE picid=%s;', [picid])
			cur.execute('DELETE picid FROM Photo WHERE picid=%s;', [picid])

			#3. delete in images
			os.remove(IMAGE_FOLDER_PREFIX + picid + '.' + pformat)

		#4. delete in Album
		cur.execute('DELETE FROM Album WHERE albumid=%s;', [albumid])

	elif op == "add":
		title = request.form.get("title")
		now = time.strftime('%Y-%m-%d', time.localtime(time.time()))
		cur.execute('INSERT into Album (title, created, lastupdated, username) VALUES (%s, %s, %s, %s);', (title, now, now, username))

	cur.execute('SELECT albumid, title FROM Album WHERE username=%s;', [username])
	all_albums=cur.fetchall()


	options = {
		"edit": True
	}
	return render_template("albums.html", username=username, albums=all_albums, **options)


@albums.route('/albums')
def albums_route():
	username = request.args.get('username')
	db = connect_to_database()
	cur = db.cursor()
	row_count = cur.execute('SELECT * FROM User WHERE username=%s;', [username])
	if row_count == 0:
		abort(404)
	cur.execute('SELECT albumid, title FROM Album WHERE username=%s;', [username])
	all_albums = cur.fetchall()
	options = {
		"edit": False
	}
	return render_template("albums.html", albums=all_albums, username=username, **options)

controllers/pic.py
from flask import *
from extensions import *
from config import *

pic = Blueprint('pic', __name__, template_folder='templates')

@pic.route('/pic', methods = ['GET', 'POST'])
def pic_route():

	db = connect_to_database()
	cur = db.cursor()
	picid = request.args.get('picid')

	cur.execute('SELECT picid FROM Photo WHERE picid=%s;', [picid])
	rows_count = cur.fetchall()
	if rows_count != 1:
		abort(404)

	#get pic format
	cur.execute('SELECT format FROM Photo WHERE picid=%s;', [picid])
	pformat = cur.fetchone()['format']

	#get albumid 
	cur.execute('SELECT albumid, sequencenum FROM Contain WHERE picid=%s;', [picid])
	photo = cur.fetchone()
	albumid = photo['albumid']
	sequencenum = photo['sequencenum']

	#prev_picid
	does_prev_pic_exist = False
	prev_picid = ""
	cur.execute('SELECT pic FROM Contain WHERE sequencenum<%s AND albumid=%s ORDER BY sequencenum DESC;', (sequencenum, albumid))
	row = cur.fetchone()
	if row is not None:
		does_prev_pic_exist = True
		prev_picid = row['picid']

	#next_picid
	does_next_pic_exist = False
	next_picid = ""
	cur.execute('SELECT pic FROM Contain WHERE sequencenum>%s AND albumid=%s ORDER BY sequencenum ASC;', (sequencenum, albumid))
	row = cur.fetchone()
	if row is not None:
		does_next_pic_exist = True
		next_picid = row['picid']


	return render_template("pic.html", albumid=albumid, picid=picid, pformat=pformat, 
							does_prev_pic_exist=does_prev_pic_exist, prev_picid=prev_picid,
							does_next_pic_exist=does_next_pic_exist, next_picid=next_picid)

templates/album.html
{% extends "base.html" %}

{% block description %}
	<h1>Album</h1>
	<p class="important">Title: {{ title['title'] }}</p>
{% endblock %}

{% block content %}
	{% if edit %}
		<div> This is only on the edit page </div>
	{% else %}
		<a href="{{ url_for('album.album_edit_route', albumid=albumid) }}">Edit View</a>
	{% endif %}

	<table>
	<tr>
		<td>Photo</td>
		{% if edit %}
			<td>Delete</td>
		{% endif %}
	</tr>

	{% for picid, format, sequencenum in picid_format_sequencenum_tuples %}
		<tr>
			<td><a href="{{ url_for('pic.pic_route', picid=picid) }}" id="pic_{{ picid }}_link"><img src="/static/images/{{ picid }}.{{ format }}" witdth=100></a></td>
			{% if edit %}
				<td>
					<form method="post", action="{{ url_for('album.album_edit_route', albumid=albumid) }}" id="delete_{{ picid }}_form">
						<input type="hidden" name="op" value="delete">
						<input type="hidden" name="picid" value="{{ picid }}">
					</form>
					<button type="submit" form="delete_{{ picid }}_form" id="delete_pic_{{ picid }}">[Delete]</button>
				</td>
			{% endif %}
		</tr>
	{% endfor %}

	</table>

	{% if edit %}
		<form method="post" action="{{ url_for('album.album_edit_route', albumid=albumid) }}" enctype="multipart/form-data" id="add_photo_form">
			<input type="file" name="file" value="file" id="file_input">
			<input type="hidden" name="op" value="add">
		</form>
		<button type="submit" form="add_photo_form" id="file_submit">[Submit]</button>
	{% end if %}

{% endblock %}

templates/albums.html
{% extends "base.html" %}
{% block description %}
    <h1>Albums - {{ username }}</h1>
{% endblock %}
{% block center %}

    {% if edit %}
        <table>
            <tr>
                <th>Album</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            {% for album in albums %}
            <tr>
                <td>{{ album['title'] }}</td>
                <td><a href="{{ url_for('album.album_edit_route', albumid=album['albumid']) }}">[Edit]</a></td>
                <td>
                    <form href="{{ url_for('albums.albums_edit_route', username=username) }}" method="POST" id="delete_{{ album['albumid'] }}_form">
                    <input type="hidden" name="op" value="delete" />
                    <input type="hidden" name="albumid" value="{{ album['albumid'] }}" />
                    </form>
                    <button type="submit" form="delete_{{ album['albumid'] }}_form" id="delete_album_{{ album['albumid'] }}">[Delete]</button>
                </td>
            </tr>
            {% endfor %}
        </table>
        <form href="{{ url_for('albums.albums_edit_route', username=username) }}" method="POST" id="add_album_form">
        New Album: <br>
        <input type="text" name="title" id="album_add_name" />
        <input type="hidden" name="op" value="add" />
        <input type="hidden" name="username" value="{{ username }}" />
        </form>
        <button type="submit" form="add_album_form" id="album_add_submit">[Add]</button>

    {% else %}
        <a href="{{ url_for('albums.albums_edit_route', username=username) }}" id='user_albums_edit{{ username }}'>Edit Albums</a>
        <table class="table">
        <thead>
            <tr>
                <td>Album</td>
            </tr>
        </thead>
        <tbody>
        {% for album in albums %}
        <tr>
            <td>
                <a href="{{ url_for('album.album_route', albumid=album['albumid']) }}" id="album_{{ album['albumid'] }}_link">{{ album['title'] }}</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>

    <link rel="stylesheet" href="/static/css/style.css" />
    <!--Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    	<meta charset="UTF-8">
    	<meta name="keywords" content="HTML,CSS">
    	<meta name="author" content="Shuqi Chen">
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Web Album</title>
    <style>
    	.thumbnail {
    		background-color: rgba(255, 255, 255, 0);
    		padding: 4px;
    		overflow: auto;
    		height: 100%;
    		width: 100%;
    		max-width: 200px;
    	}

    	#footer {
    		clear: both;
    		text-align: center;
    		padding: 5px;
    	}

        .padding-bottom-20 {
            padding-bottom: 20px;
        }

    </style>
</head>
<body role="document">
	<div class="center">
        <h1>Hello, World Wide Web</h1>
        {% block description %}{% endblock %}
        <div class="padding-bottom-20"></div>
        {% block content %}{% endblock %}
    </div>
    <script type="text/javascript" src="/static/js/main.js"></script>
</body>
<footer>
    <p>&copy;2017 by Shuqi Chen</p>
</footer>

</html>

templates/index.html
{% extends "base.html" %}


{% block description %}
	<p class="center">Welcome! This is a simple online photo service. Feel free to create and edit your albums. </p>
{% endblock %}

{% block content %}
	<table border="2">
		<tr>
			<td>
				Username
			</td>
		</tr>
		{% for user in users %}
		<tr>
			<td>
			<a href="{{ url_for('albums.albums_route', username=user['username']) }}"
			   id="user_album_{{ user['username'] }}">
			</td>
		</tr>
		{% endfor %}
	</table>

{% endblock %}

templates/pic.html
{% extends "base.html" %}

{% block content %}
	<h1>PIC</h1>
{% endblock %}

{% block content %}
	<img src="static/images/{{ picid }}.{{ pformat }}">
	{% if does_prev_pic_exist %}
	<a href="{{ url_for('pic.pic_route', picid=prev_picid) }}" id="prev_pic">Previous</a>
	{% endif %}

	{% if does_next_pic_exist %}
	<a href="{{ url_for('pic.pic_route', picid=next_picid) }}" id="next_pic">Next</a>
	{% endif %}

	<a href="{{ url_for('album.album_route', albumid=albumid) }}" id="parent_album">Back to Album</a>

{% endblock %}